alias home="cd ~"
alias btop="btop --utf-force"
alias aliaslist="grep --only-matching '^alias\s\w*' .zshrc" 

alias confsway="sudo nano .config/sway/config"
alias confbar="sudo nano .config/waybar/config"
alias confbars="sudo nano .config/waybar/style.css"
alias confterm="sudo nano .config/alacritty/alacritty.yml"
alias confsh="sudo nano .zshrc"

alias pyserver="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/server/server.py"
alias pipinstaller="/home/joey/JoeyRepositories/Terminal-Projects/linuxsh/pippackages.sh"
alias calculator="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/calculator/simplecalculator.py"
alias clicker="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/autoclicker/clicker.py"
alias idleclicks="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/autoclicker/idleclicker.py"
alias afk="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/idlecursor/afkcursor.py"
alias idlescroller="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/idlescroller/idlescroller.py"
alias textspam="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/spambot/spam.py"
alias filespam="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/spambot/filespam.py"
alias keylogger="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/keylogger/keylogger.py"
alias birthday="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/birthdaywisher/happybirthday.py"
alias meditate="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/meditation/meditate.py"
alias netspeed="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/internetspeed/speedprinter.py"
alias wolfram="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/wolramalpha/apicaller.py"
alias voassist="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/voiceassistant/voasst.py"
alias votyper="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/voiceassistant/voicetyper.py"
alias TTS="/bin/python /home/joey/JoeyRepositories/Python-Projects/completed/voiceassistant/TTS.py"

alias meet="/home/joey/JoeyRepositories/Python-Projects/completed/selenium/meetauto.sh"
alias twitterbot="/home/joey/JoeyRepositories/Python-Twitter-Bot/twitterbot.sh"
alias redditbot="/home/joey/JoeyRepositories/.Other-User-Repositories/Python-Reddit-Bot/redditbot.sh"
alias discordbot="/home/joey/JoeyRepositories/Python-Discord-bot/discordbot.sh"

alias adbcheck="/home/joey/JoeyRepositories/Android-Projects/adbcheck.sh"
alias adbrestart="/home/joey/JoeyRepositories/Android-Projects/adbrestart.sh"
alias scrcpystart="/home/joey/JoeyRepositories/Android-Projects/scrcpystart.sh"
alias scrcpyrec="/home/joey/JoeyRepositories/Android-Projects/scrcpyrec.sh"